name: Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to server
        run: |
          echo "${{ secrets.GCP_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          tar czf - . | ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_SERVER_IP }} "mkdir -p ~/app && tar xzf - -C ~/app"
      # - name: Run Docker on server
      #   run: |
      #     ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_SERVER_IP }} << 'EOF'
      #       cd /home/${{ secrets.GCP_USER }}/app
      #       docker-compose 
            
      #     EOF